2024-12-15 12:49:43,442 - INFO - Application started
2024-12-15 12:50:21,804 - INFO - ----------Processing loop started----------
2024-12-15 12:50:45,208 - INFO - ----New round of detections----
2024-12-15 12:50:47,297 - CRITICAL - Critical error in while loop
Traceback (most recent call last):
  File "c:\Users\User\OneDrive - Afeka College Of Engineering\שולחן העבודה\final Project - Eye sight\code\main_with_gui.py", line 221, in processing_loop
    results_l, frame_l = detector.detect_and_describe(frame=frame, save_images=SAVE_IMAGES, camera_index=camera_index)
  File "c:\Users\User\OneDrive - Afeka College Of Engineering\שולחן העבודה\final Project - Eye sight\code\OOP_yolo_detector.py", line 49, in detect_and_describe
    results = self.model(frame, size=self.img_size)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\User/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 880, in forward
    im = im.transpose((1, 2, 0))  # reverse dataloader .transpose(2, 0, 1)
ValueError: axes don't match array
2024-12-15 12:50:47,381 - INFO - The video ended and now the App will be close! Bey Bey
